modLoader = "javafml"
loaderVersion = "[2,)"
license = "GPL-3.0 license"

[[mods]]
modId = "photon"
version = "2.1.5"
displayName = "Photon"
authors = "KilaBash"
description = "Photon, a VFX library"
logoFile = "icon.png"
displayURL = "https://github.com/Low-Drag-MC/Photon/"
issueTrackerURL = "https://github.com/Low-Drag-MC/Photon/issues"
[[mixins]]
config="photon.mixins.json"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.photon]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0.0-alpha,)"
    ordering = "NONE"
    side = "CLIENT"
[[dependencies.photon]]
    modId = "minecraft"
    type = "required"
    versionRange = "1.21.1"
    ordering = "NONE"
    side = "CLIENT"
[[dependencies.photon]]
    modId = "ldlib2"
    type = "required"
    versionRange = "[2.2.24,)"
    ordering = "AFTER"
    side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
[features.photon]
openGLVersion="[3.2,)"
